#sudo: required
#dist: trusty
#
#addons:
#  chrome: stable
#
#
#install:
#  - cp .env.travis .env
#  - composer self-update
#  - travis_retry composer install --no-interaction --prefer-source
#
#before_script:
#  - mysql -e 'create database pingtocoffee_test;'
#  - php artisan migrate --force
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#  - php artisan serve &
#
#script:
#  - php artisan key:generate
#  - phpunit
#  - php artisan dusk
sudo: required

dist: trusty

language: php

php:
  - '7.2'

addons:
   chrome: stable
   hosts:
     - pingtocoffee.io

install:
   - cp .env.travis .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
   - mysql -e 'create database pingtocoffee_test;'
   - php artisan migrate --force
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://pingtocoffee.io &
   - php artisan serve &

script:
   - php artisan dusk