language: php

php:
  - '7.2'

sudo: false

install:
 - cp .env.travis .env
 - composer self-update
 - travis_retry composer install --no-interaction --prefer-source

before_script:
  - mysql -e 'create database pingtocoffee_test;'
  - php artisan migrate --force --seed

script:
 - php artisan key:generate
 - vendor/bin/phpunit
